ASP2236903/Models/producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP2236903.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.producto_imagen = new HashSet<producto_imagen>();
            this.producto_compra = new HashSet<producto_compra>();
        }
    
        public int id { get; set; }
        [Required]
        public string nombre { get; set; }
        [Required]
        public int percio_unitario { get; set; }
        [Required]
        public string descripcion { get; set; }
        [Required]
        public int cantidad { get; set; }
        public int id_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_imagen> producto_imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_compra> producto_compra { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}

ASP2236903/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP2236903.Models;
using Rotativa;
using System.IO;
using ASP2236903.Filtros;

namespace ASP2236903.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities())
            {
                return View(db.producto.ToList());
            }
        }

        public static string NombreProveedor(int idProveedor)
        {
            using (var db = new inventario2021Entities())
            {
                return db.proveedor.Find(idProveedor).nombre;
            }
        }

        public ActionResult ListarProveedores()
        {
            using (var db = new inventario2021Entities())
            {
                return PartialView(db.proveedor.ToList());
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(producto producto)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var db = new inventario2021Entities())
                {
                    db.producto.Add(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities())
            {
                var producto = db.producto.Find(id);
                //conusltando de la tabla producto_iamgen las imagenes del producto
                var imagen = db.producto_imagen.Where(e => e.id_producto == producto.id).FirstOrDefault();
                //pasando la ruta a la vista
                ViewBag.imagen = imagen.imagen;
                return View(producto);
            }
        }

        public ActionResult Edit(int id)
        {
            using (var db = new inventario2021Entities())
            {
                producto productoEdit = db.producto.Where(a => a.id == id).FirstOrDefault();
                return View(productoEdit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(producto productoEdit)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    var oldProduct = db.producto.Find(productoEdit.id);
                    oldProduct.nombre = productoEdit.nombre;
                    oldProduct.cantidad = productoEdit.cantidad;
                    oldProduct.descripcion = productoEdit.descripcion;
                    oldProduct.percio_unitario = productoEdit.percio_unitario;
                    oldProduct.id_proveedor = productoEdit.id_proveedor;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    producto producto = db.producto.Find(id);
                    db.producto.Remove(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        [AuthorizeUser(idRol: 1)]
        public ActionResult cargarImagen()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult cargarImagen(int producto, HttpPostedFileBase fileForm)
        {
            //string para guardar la ruta
            string filePath = string.Empty;
            string name = "";

            //condicion para saber si el archivo llego
            if (fileForm != null)
            {
                //ruta de la carpeta que guardara el archivo
                string path = Server.MapPath("~/Uploads/Imagenes/");

                //condicion para saber si la carpeta uploads existe
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                name = Path.GetFileName(fileForm.FileName);
                //obtener el nombre del archivo
                filePath = path + Path.GetFileName(fileForm.FileName);

                //obtener la extension del archivo
                string extension = Path.GetExtension(fileForm.FileName);

                //guardar el archivo
                fileForm.SaveAs(filePath);


            }


            using (var db = new inventario2021Entities())
            {
                var imagenProducto = new producto_imagen();
                imagenProducto.id_producto = producto;
                imagenProducto.imagen = "/Uploads/Imagenes/" + name;
                db.producto_imagen.Add(imagenProducto);
                db.SaveChanges();
            }

            return View();
        }
    }
}

ASP2236903/Views/Producto/Create.cshtml
@model ASP2236903.Models.producto

@{
    ViewBag.Title = "Registrar Producto";
}

<h2>Registar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2" for="nombre">Nombre:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="percio_unitario">Precio Unitario:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.percio_unitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.percio_unitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="descripcion">Descripción:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="cantidad">Cantidad:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="id_proveedor">Proveedor:</label>
            <div class="col-md-10">
                @Html.Action("ListarProveedores")
                @Html.ValidationMessageFor(model => model.id_proveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ver Todos", "Index")
</div>

ASP2236903/Views/Producto/Details.cshtml
@model ASP2236903.Models.producto

@{
    ViewBag.Title = "Detalles de Producto";
}

<h2>Detalles</h2>

<div>
    <h4>Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            Precio Unitario:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.percio_unitario)
        </dd>

        <dt>
            Descripción:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            Cantidad:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cantidad)
        </dd>

        <dt>
            Proveedor:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_proveedor)
        </dd>

        <dt>
            Imagen
        </dt>

        <dd>
            <img class="img-responsive" src="@Url.Content("~/" + ViewBag.imagen)" alt="Image" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Ver Todos", "Index")
</p>

ASP2236903/Views/Producto/Edit.cshtml
@model ASP2236903.Models.producto

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Producto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            <label class="control-label col-md-2" for="nombre">Nombre:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="percio_unitario">Precio Unitario:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.percio_unitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.percio_unitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="descripcion">Descripción:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="cantidad">Cantidad:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="proveedor">Proveedor:</label>
            <div class="col-md-10">
                @Html.Action("listarProveedores")
                @Html.ValidationMessageFor(model => model.id_proveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ver Todos", "Index")
</div>

ASP2236903/Views/Producto/Index.cshtml
@model IEnumerable<ASP2236903.Models.producto>

@{
    ViewBag.Title = "Lista de Productos";
}

<h2>Lista Productos</h2>

<p>
    @Html.ActionLink("Crear Producto", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Nombre Producto
        </th>
        <th>
            Precio Unitario
        </th>
        <th>
            Descripción
        </th>
        <th>
            Cantidad
        </th>
        <th>
            Proveedor
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.percio_unitario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @ASP2236903.Controllers.ProductoController.NombreProveedor(item.id_proveedor)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.id }, new {@class = "linkDelete"})
            </td>
        </tr>
    }

</table>

@section scripts
{
    <script>
        $(".linkDelete").click(function (event) {
            if (!confirm('¿Esta seguro de eliminar?')) {
                event.preventDefault();
            }
        })
    </script>
}

ASP2236903/Views/Producto/ListarProveedores.cshtml
@model IEnumerable<ASP2236903.Models.proveedor>

<select class="form-control" id="id_proveedor" name="id_proveedor">
    @foreach (var item in Model)
    {
        <option value="@item.id">@item.nombre</option>
    }
</select>

ASP2236903/Views/Producto/cargarImagen.cshtml
@{
    ViewBag.Title = "Cargar Imagen";
}

<h2>Cargar CSV</h2>

@using (Html.BeginForm("cargarImagen", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="control-label col-md-2">Cargar CSV</label>
        <div class="col-md-10">
            <input type="file" name="fileForm" class="form-control" required />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Id Producto</label>
        <div class="col-md-10">
            <input type="number" name="producto" class="form-control" required />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Enviar" />
        </div>
    </div>

}

<img src="@Url.Content("~/Uploads/Imagenes/firma.png")" alt="Image" />